[package]
name = "example"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-log-ebpf = { path = "../aya-log-ebpf" }

[[bin]]
name = "example"
path = "src/main.rs"
